import { createStyles } from "@mantine/core";

export const useStyles = createStyles((theme, _params, getRef) => ({
  cardWrapper: {
    display: "inline-flex",
    justifyContent: "flex-end",
  },
  contentCard: {
    transition: `all .2s ease-in-out`,
    minHeight: 292,
    minWidth: 292,
  },
  cardContentOverlay: {
    position: "absolute",
    height: "100%",
    width: "100%",
    borderRadius: theme.spacing.lg,
    top: 0,
    left: 0,
    background: theme.fn.linearGradient(
      180,
      theme.fn.rgba(theme.colors.dark[9], 0.1),
      theme.fn.rgba(theme.colors.dark[9], 0.9)
    ),
    display: "inline-flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    padding: `${theme.spacing.xl}px ${theme.spacing.md}px`,
  },
  modalContentContainer: {
    position: "relative",
    width: "100%",
    height: "100%",
    display: "inline-flex",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  imageWrapper: {
    position: "relative",
    minHeight: 680,
    // width: "100%",
    Width: "85%",
    display: "inline-flex",
    justifyContent: "center",
    alignItems: "center",
  },
  slider: {
    width: "100%",
  },
  arrowLeft: {
    position: "absolute",
    left: 0,
    minHeight: "100%",
    width: 120,
    display: "inline-flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    zIndex: 100,
  },
  arrowRight: {
    position: "absolute",
    right: 0,
    minHeight: "100%",
    width: 120,
    display: "inline-flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    zIndex: 100,
  },
  closeModal: {
    display: "inline-flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    position: "absolute",
    top: 0,
    right: 0,
    width: 120,
    height: 80,
    zIndex: 200,
  },
}));
